import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'
import Navbar from '@/components/SharedComp/Header/Navbar'
import Hero from '@/components/Home-Components/Hero/Hero'
import Button2 from '../../experimentComponents/buttons/button2/Button2'
import AboutMe from '@/components/Home-Components/AboutMe/AboutMe'
import CaraouselSection from '@/components/Home-Components/CaraouselSection/CaraouselSection'
import PastClientSection from '@/components/Home-Components/PastClientSection/PastClientSection'
import Footer from '@/components/SharedComp/Footer/Footer'
import Aos from 'aos'
import 'aos/dist/aos.css';
import { useEffect, useState } from 'react'
import PastClientCaraousel from '@/components/SharedComp/pastClientCaraousel/PastClientCaraousel'
import NavFootLayout from '@/components/SharedComp/NavFootLayout/NavFootLayout'
import { db } from '../../firebase.init'
import { collection, getDocs } from 'firebase/firestore'
import Loading from '@/components/SharedComp/Loading/Loading'
import HomeClient from '@/components/Home-Components/PastClientSection/HomeClientSection/HomeClient'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  useEffect(() =>{
    Aos.init();

  },[])

   //GET DATA HERE
   const [data,setData] = useState([])
   const databaseRef = collection(db,'homepage')
   const [loading,setLoading] = useState(true)
   useEffect(() =>{
       getData()
     },[])
  
     const getData = async () => {
      await getDocs(databaseRef).then((response) => {
        setLoading(false);
        if (response.docs.length > 0) {
          setData(response.docs[0].data());
        }
      });
    };

 

  return (
    <NavFootLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <main >
        <div className={styles.main}>
          {loading? <Loading/> :
          <>
            <Hero data={data} />
            <AboutMe />
            <CaraouselSection/>
            <HomeClient/>
            <PastClientCaraousel/> 
          </>}
         
        </div>
        
      </main>
    </NavFootLayout>
  )
}
